FROM --platform=$BUILDPLATFORM traction:plugins-acapy
#If you get an error saying that image unknown, new builds should replace the first line with the following one, the name of the image has been changed.
#FROM --platform=$BUILDPLATFORM docker.io/sajib2hassan/traction:plugins-acapy

USER root

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY ngrok-wait.sh ngrok-wait.sh
RUN chmod +x ./ngrok-wait.sh

USER $user
